version: "2"
services:
  node:
    image: "node"
    ports:
      - "80:3000"
    volumes:
      - "./:/app/"
    links:
      - memcache
    working_dir:
      "/app/bin/"
    command: "npx nodemon ./app.js --watch ../src/"
  memcache:
    image: "memcached"
    ports:
      - "11211:11211"
